events { 
    worker_connections 1024; 
}

http {
    # تعريف مجموعة الحاويات التي ستستقبل الضغط (Upstream Cluster)
    upstream backend_servers {
        server app_01:8000;
        server app_02:8000;
    }

    server {
        listen 80;

        # استقبال أي طلب قادم للموقع وتوجيهه للمجموعة
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

